### ISSUE TITLE
edu.arizona.sista.learning.TestSVMRankingClassifier errors upon assembly

### ISSUE THREAD

**Issue by matanster** [sistanlp/processors#17]
I am not sure this is a realy issue (maybe only a local setup issue), but I have tried to build from trunk today (sbt `compile` and `assembly`, after integrating [sbt-assembly 0.11.2](https://github.com/sbt/sbt-assembly/tree/0.11.2)), and got some errors:

```
Finished all threads.
Estimated thread times:
Thread #0: 11309.0
Thread #1: 9942.0
[info] ScalaTest
[info] Run completed in 5 minutes, 21 seconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] Failed: Total 36, Failed 2, Errors 0, Passed 34
[error] Failed tests:
[error] 	edu.arizona.sista.learning.TestSVMRankingClassifier
[error] (core/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 427 s, completed Jan 3, 2015 3:34:15 PM
```

Does the SVM require a certain minimum of free memory or any other special requirement? I did not notice any specific error other than above.

**Comment by MihaiSurdeanu** [comment]
I suspect this is an installation issue for svm_rank. Can you please look at the error log? I would put my money on not having the sum_rank directory in your $PATH.
All tests should pass.

**Comment by matanster** [comment]
Thanks, I guess that's the problem. I only added the BANNER variable to the environment.

**Comment by MihaiSurdeanu** [comment]
Good!
And yes, that is an ugly dependency... We'll try to fix it, but it's tricky, as the code who needs it is distributed only in binary form.
