### ISSUE TITLE
Version 5.0 is not in maven central

### ISSUE THREAD

**Issue by zoharsacks** [sistanlp/processors#20]
1. Adding the dependencies to pom file.
2. Running maven->Reinport in intellj IDEA.

Expected - dependencies are recognized.
Actual - maven reports error on version 5.0.

NOTE: I have checked versions at  [maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22edu.arizona.sista%22%20AND%20a%3A%22processors%22) latest version is 3.3.

**Comment by MihaiSurdeanu** [comment]
Hi Zohar,

processors is now released following sbt principles, which means adding 2.11 as a suffix to the artifact name. See:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22edu.arizona.sista%22%20AND%20a%3A%22processors_2.11%22

**Comment by zoharsacks** [comment]
Hi Mihai,

Thank you for the swift response, now it works (YEY...)
This should be mentioned in the documentation so I have added it and submitted a pull request
