### ISSUE TITLE
Issue in Dependency Resolution.

### ISSUE THREAD

**Issue by brahmbhattspandan** [sistanlp/processors#22]
I am trying to download SBT dependencies by adding following lines in build.sbt

libraryDependencies ++= Seq(
    "edu.arizona.sista" %% "processors" % "5.0",
    "edu.arizona.sista" %% "processors" % "5.0" classifier "models",
)

However this depends internally on following dependencies

"edu.arizona.sista" %% "banner" % "1.0-SNAPSHOT",
 "edu.arizona.sista" %% "banner" % "1.0-SNAPSHOT" classifier "dragontool",
 "edu.arizona.sista" %% "banner" % "1.0-SNAPSHOT" classifier "heptag"

The banner dependencies are not getting resolved by SBT.

My Scala version is  := "2.11.5"

Is there a way to keep Banner as a managed dependency ?

The error is as follow 

 sbt.ResolveException: unresolved dependency: edu.arizona.sista#banner_2.11;1.0-SNAPSHOT: not found
(*:31mupdate0m) sbt.ResolveException: unresolved dependency: edu.arizona.sista#banner_2.11;1.0-SNAPSHOT: not found

**Comment by MihaiSurdeanu** [comment]
Yes, this is ugly. We had no choice because banner distributes some of its jars only as binary.

In any case, we are working on replacing banner with our own tool for 5.1, which hopefully will be released within a week. Meanwhile, if you want to use 5.0, please install our fork of banner first:
https://github.com/sistanlp/banner

**Comment by MihaiSurdeanu** [comment]
I just released 5.1, which replaces Banner with our own tool. 
We now only use pure maven dependencies.

**Comment by brahmbhattspandan** [comment]
Yes its downloading the dependency perfectly fine. 

However there is another issue (not sure if thats from my side or the library)

On downloading the dependency and running the code provided in your readme file, the code gets stuck loading the RST Parser

[main] DEBUG e.a.s.discourse.rstparser.RSTParser - Loading RST parsing model from: edu/arizona/sista/discourse/rstparser/model.const.rst.gz


I checked the reference library and and the model is there in processors_211-5.1.jar


Could you let me know if I am doing something wrong?

**Comment by hickst** [comment]
Hi brahmbhattspandan,

The parsing model is by-far the largest component of the whole library and requires a good bit of memory to run. Please allocate at least 4G for your Java heap space (6G is better). I regularly run with Java8 JAVA_OPTS set to '-server -Xms1024m -Xmx6144m'.
   regards,
        -tom hicks SISTA Research Programmer

**Comment by brahmbhattspandan** [comment]
Worked perfectly fine.  Thanks for the prompt resolution Mihai Surdeanu and Tom Hicks.

Just a suggestion if you can put this heap size recommendation in readme file. Beginners like me would find it really helpful.
