### ISSUE TITLE
example code can't be compiled   

### ISSUE THREAD

**Issue by adam-faulkner** [sistanlp/processors#26]
I get the following error when I try to compile your example code:

```
Incompatible types: String cannot be converted to Document
        Document doc = proc.annotate("John Smith went to China. He visited Beijing, on January 10th, 2013.");
```
Fix?

**Comment by MihaiSurdeanu** [comment]
Can you please send your complete class and build.sbt file?
Alternatively, can you try to build your example based on edu.arizona.sista.processors.ProcessorExample?

**Comment by marcovzla** [comment]
Seems like you are using java. The method you are trying to call has a second argument that defaults to `false`:
```
def annotate(text:String, keepText:Boolean = false)
```

Java doesn't seem to recognize the default argument. Can you try setting it explicitly?
```
Document doc = proc.annotate("John Smith went to China. He visited Beijing, on January 10th, 2013.", false);
```

**Comment by adam-faulkner** [comment]
@marcovzla  That did it! Thanks :-)

**Comment by marcovzla** [comment]
@adam-faulkner Great!
@MihaiSurdeanu maybe we should include a java example in the readme for issues like this?

**Comment by hickst** [comment]
There is a java example already. It is probably what Mr. Faulkner was using:

https://github.com/sistanlp/processors#using-processors-from-java

**Comment by marcovzla** [comment]
I see, I will add the missing argument.
