### ISSUE TITLE
Multi-label classifier

### ISSUE THREAD

**Issue by omidb** [sistanlp/processors#28]
Hi,

I wanted to ask if your earning package has any support for multi-label classification, if yes, how can I use it? i couldn't find any example.

thanks,

**Comment by MihaiSurdeanu** [comment]
Hi Omid,

All the classifiers implementing the edu.arizona.sista.learning.Classifier trait support multi-label classification by default. The method scoresOf returns the scores (usually probabilities) for all the labels.
See for example, edu.arizona.sista.learning.TestLiblinearClassifier, TestPerceptronClassifier, or TestRandomForestClassifier.

Mihai

**Comment by omidb** [comment]
@MihaiSurdeanu I thought these are Multi-Class not Multi-Label, so if they are multi-label how can I assign multiple label into classifier? will this work:
```scala
val classifier = new LiblinearClassifier[String, List[String]](bias = false)
```

**Comment by MihaiSurdeanu** [comment]
I see what you mean. In my hurry to reply, I thought you meant multi-class.
No, we do not support multi-label classification yet. You can check my other project, which is designed around multi-label classification:
http://nlp.stanford.edu/software/mimlre.shtml

I plan to include this in processors at some point. But, for now, it is a separate Java project.
Mihai

**Comment by omidb** [comment]
@MihaiSurdeanu thanks! Including that would be great!
